#! /bin/sh

export PKG_EXT="kpm"
export VERBOSE=0
#Desabilita suporte a unicode, para melhor performance
export LC_ALL=C
export LANG=C

CHECK() {
pkg_name="$@"

 if ! echo ${pkg_name} | grep -E "\b${PKG_EXT}\b$" ; then 
   printf '%b' "Extensao invalida\nPacote deve ser ${PKG_EXT}\n"
   return 1
 fi

 if echo "$pkg_name" | grep -qE "[[:space:]]+" ; then
  printf '%b' "Nao utilizar espacos\n"
  printf '%b' "Abortar\n"
  return 1
 fi

 QNT_HIFEN=`echo "$pkg_name" | grep -o "-" | wc -l `
 
 if [ "$QNT_HIFEN" -lt '2' ] || [ "$QNT_HIFEN" -gt '2' ] ; then 
  printf '%b' "Nome invalido!\nO nome so pode ter dois hifens: 'pacote-versao-build.kpm'\n"
  return 1
 fi
}

CREATE_PKG() {
 pkg_name="$1"
 PKG_INFO="info/pkginfo"
 DIR_INFO="info"

 if [ ! -e "$PKG_INFO" ] && [ ! -z "$DIR_INFO" ] ; then
   printf '%b' "Necessario criar o arquivo 'pkginfo' na pasta 'info'\n"
   exit 1
 fi

 if [ "$VERBOSE" -eq '1' ] ; then
    if tar -vcf ../${pkg_name} .; then
       printf '%b' "Pacote ${pkg_name} criado com sucesso\n"
       return 0
    else
       printf '%b' "Erro ao criar pacote ${pkg_name}\n"
       exit 1
    fi
 else
    if  tar -cf ../${pkg_name} .; then
       printf '%b' "Pacote ${pkg_name} criado com sucesso\n"
       return 0
    else 
       printf '%b' "Pacote ${pkg_name} nao foi criado\n"
       exit 1
    fi
 fi

}

USAGE() {
 cat << EOF
createpkg [opcoes]

create, -c	Cria pacote
verbose, -v 	Mostra o verbose da criacao do pacote
EOF
return 0
}

if [ -z "$1" ] ; then
 USAGE
fi

while [ -n "$1" ] ; do
 case $1 in
  create|-c)
   CMD=$1
   shift
   ;;
  verbose|-v)
   VERBOSE=1
   shift
   ;;
  *.kpm)
  PKG=$1
  shift
  ;;
 *)
  USAGE 
  exit 0
  ;;
 esac
done

case "$CMD" in
 create|-c)
   if [ -z "$CMD" ] ; then
    printf '%b'"Voce precisa informar nome do pacote\n"
    exit 1 
   fi
   CHECK "$PKG" || exit 1
   CREATE_PKG "$PKG"
  ;;
esac
